### ISSUE TITLE
Cryptic error when value and key of field are the same

### ISSUE THREAD

**Issue by LillySchramm** [EliasSchramm/EPS-Packages#1]
> This is only here to remind me once I have time to iterate over my projects.

When trying to send a package that has a field that has its key as value, for example ```add("password","password")```, the folowing error gets thrown and the package does not get send.

```java
java.lang.IllegalStateException: zip file closed
   at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:828)
   at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:327)
   at java.base/java.util.jar.JarFile.getEntry(JarFile.java:513)
   at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:468)
   at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154)
   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
   at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:104)
   at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
   at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
   at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3305)
   at java.base/java.lang.Class.getConstructor0(Class.java:3510)
   at java.base/java.lang.Class.getConstructor(Class.java:2238)
   at de.epsdev.packages.packages.Package.toPackage(Package.java:42)
   at de.epsdev.packages.packages.PackageCache.process(PackageCache.java:57)
  at de.epsdev.packages.Connection.run(Connection.java:41)
```

**Comment by LillySchramm** [comment]
- But only sometimes....

**Comment by LillySchramm** [comment]
Found the issue: My specific application probably allready started unloading classes when construction of the package happend.
